-- MySQL Script generated by MySQL Workbench
-- Thu Sep  8 18:01:09 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema autoadvisor
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema autoadvisor
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `autoadvisor` DEFAULT CHARACTER SET utf8 ;
USE `autoadvisor` ;

-- -----------------------------------------------------
-- Table `autoadvisor`.`Class`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autoadvisor`.`Class` (
  `classId` INT NOT NULL AUTO_INCREMENT,
  `subject` VARCHAR(45) NULL,
  `classNum` INT NULL,
  `longName` VARCHAR(100) NULL,
  `shortName` VARCHAR(45) NULL,
  `credits` INT NULL,
  `grade` VARCHAR(2) NULL,
  PRIMARY KEY (`classId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autoadvisor`.`requiredList`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autoadvisor`.`requiredList` (
  `classId` INT NOT NULL,
  `credits` INT ZEROFILL NULL,
  PRIMARY KEY (`classId`),
  CONSTRAINT `fk_table1_Class`
    FOREIGN KEY (`classId`)
    REFERENCES `autoadvisor`.`Class` (`classId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autoadvisor`.`pickLists`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autoadvisor`.`pickLists` (
  `listId` INT NOT NULL AUTO_INCREMENT,
  `credits` INT NULL,
  PRIMARY KEY (`listId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autoadvisor`.`pickList`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autoadvisor`.`pickList` (
  `classId` INT NOT NULL,
  `listId` INT NOT NULL,
  PRIMARY KEY (`classId`, `listId`),
  INDEX `fk_table2_table31_idx` (`listId` ASC) VISIBLE,
  CONSTRAINT `fk_table2_Class1`
    FOREIGN KEY (`classId`)
    REFERENCES `autoadvisor`.`Class` (`classId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_table2_table31`
    FOREIGN KEY (`listId`)
    REFERENCES `autoadvisor`.`pickLists` (`listId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autoadvisor`.`schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autoadvisor`.`schedule` (
  `classId` INT NOT NULL,
  `startTime` TIME NULL,
  `endTime` TIME NULL,
  `season` VARCHAR(7) NULL,
  `inClass` INT NULL,
  `classMax` INT NULL,
  `year` YEAR NULL,
  PRIMARY KEY (`classId`),
  CONSTRAINT `fk_table4_Class1`
    FOREIGN KEY (`classId`)
    REFERENCES `autoadvisor`.`Class` (`classId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autoadvisor`.`prereq`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autoadvisor`.`prereq` (
  `classToTakeId` INT NOT NULL,
  `ClassNeededId` INT NOT NULL,
  PRIMARY KEY (`classToTakeId`),
  INDEX `fk_prereq_Class2_idx` (`ClassNeededId` ASC) VISIBLE,
  CONSTRAINT `fk_prereq_Class1`
    FOREIGN KEY (`classToTakeId`)
    REFERENCES `autoadvisor`.`Class` (`classId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_prereq_Class2`
    FOREIGN KEY (`ClassNeededId`)
    REFERENCES `autoadvisor`.`Class` (`classId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
